name: Java CI
on: push
jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: ci/build-app.sh
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-Down
    steps:
      - name: Test
        run: ci/unit-test-app.sh
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Test
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .